# Generated by Django 4.2.4 on 2023-11-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('editorial', models.CharField(max_length=50)),
                ('anio_publicacion', models.IntegerField()),
                ('archivo', models.FileField(upload_to='archivos_libros/')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Devuelto', 'Devuelto')], max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesApp.libro')),
            ],
        ),
    ]
